apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: task-manager-api
  annotations:
    github.com/project-slug: Mauriceac/task-manager-api
spec:
  type: other
  lifecycle: unknown
  owner: guests
